### ISSUE TITLE
List dependencies

### ISSUE THREAD

**Issue by ltratt** [softdevteam/warmup_stats#10]
It's not really clear what dependencies need to be installed for `build.sh` to succeed -- they're not documented or (mostly) checked for. I've added a couple of checks (in https://github.com/softdevteam/warmup_stats/pull/9) for things that caused problems on Tom's machine, but it's incomplete. That's going to make it hard for people to install this stuff easily.

**Comment by snim2** [comment]
Now we have `INSTALL.md` I think we can close this issue?

**Comment by ltratt** [comment]
Agreed.
