### ISSUE TITLE
HTML tables: replace classifications with images

### ISSUE THREAD

**Issue by snim2** [softdevteam/warmup_stats#39]
As in the LaTeX tables, we would prefer to use symbols for benchmark classifications, without packaging PNGs with the HTML tables.

**Comment by ltratt** [comment]
Although I tend to agree that we don't want PNGs, it's not *impossible* to do this nicely. One can use bas64 encoding to embed PNGs directly in HTML. e.g. http://www.greywyvern.com/code/php/binary2base64
