### ISSUE TITLE
Windows 10 support?

### ISSUE THREAD

**Issue by smarr** [softdevteam/warmup_stats#66]
Hey, just a question:

Did anyone try warmup_stats on Windows 10, without the Linux environment it supports?

If not, how likely is it going to work?

Thanks!

**Comment by ltratt** [comment]
Our basic intention is that warmup_stats works on Unix more-or-less out of the box. It works under the Win 10 Linux environment and I'd consider that to be supported. It's not likely to work on "normal" Windows out of the box, and I'm not sure if it's worth fixing that, given that it works easily under the Linux environment.

I expect that the first problem you'll have under "normal" Windows is that the build script won't work; I have no idea how easy the dependencies might be to install, but I imagine they're mostly not *too* hard. Then `warmup_stats` itself makes some Unix-y path assumptions that would have to be fixed one by one. None of those are likely to require rocket science fixes, but it'll be hard to know how many things there are to be fixed are until it's tried. We'd happily merge suitable porting PRs, but we don't have the bandwidth to do this porting ourselves.

**Comment by smarr** [comment]
Ok, thanks.

Just one comment, because you mentioned it.
`build.sh` is somewhat broken. [There is an expectation for a `work` directory](https://github.com/softdevteam/warmup_stats/blob/master/build.sh#L29), which does not exist.

**Comment by ltratt** [comment]
Erp, that's a bug. Will fix.

**Comment by ltratt** [comment]
I'm a bit surprised because this looks like it should work:

```sh
HERE_DIR=$(dirname $(readlink -f "$0"))
R_INST_DIR=${HERE_DIR}/work/R-inst
mkdir -p ${R_INST_DIR}
```

Although I vaguely remember that `readlink` on OS X doesn't have the `-f` option. Are you running on OS X?

**Comment by smarr** [comment]
Hm, no, just looking at it again, there is a `mkdir -p` above. Strange. Not sure what went wrong. Never mind :)
