### ISSUE TITLE
Benchmarking diffing

### ISSUE THREAD

**Issue by ltratt** [softdevteam/warmup_stats#7]
At the moment we have no way of telling people if/when benchmark performance has changed. Put another way, let's say we benchmark B, change something about the corresponding VM, then benchmark B again. What do we have to do to see if things got better/worse/didn't change? We have to check the two PDFs manually to see if means and confidence intervals overlap, which is incredibly fiddly and easy to get wrong.

As a simple thing, what we could do is have a sub-command which takes two results files (Rbefore and Rafter) in and spits out a PDF which contains something like: all Rbefore's results as per normal; all Rafter's results coloured by whether they're faster (black), the same (grey), or slower (red) than Rbefore's results.

**Comment by snim2** [comment]
We should probably use the code we wrote for Figure 9 (or was it 10?) for the paper, which tests whether two benchmarks have overlapping confidence intervals.

**Comment by ltratt** [comment]
I think it's the code from Figures 9 and 11.
