### ISSUE TITLE
Allow diffing against diffently named VM's

### ISSUE THREAD

**Issue by fsfod** [softdevteam/warmup_stats#71]
It would make things much simpler when comparing different VMs for the same language to allow specifying the _before_ and _after_ VM name from the result file that are diffed against with some command line option. 
A small addition to go along with this could be the title in the generate pdf\html file to be something like "BeforeVMName vs AfterVMName" when this mode is used.

**Comment by snim2** [comment]
Should this only be available in the `diff_results` script, or does it also need to be added to the `warmup_stats` front-end?
